CREATE TABLE clients
(
	UserId SERIAL PRIMARY KEY,
	UserName CHARACTER VARYING(50),
	UserSurname CHARACTER VARYING(50),
	UserBirthDay DATE,
	UserPassport CHARACTER VARYING(15),
	UserPhone CHARACTER VARYING(15)
);